### negation
%v_neg_1ps_prs :: i do not [pos=v,+neg,sb=[+p1,-plr],tm=imf] ; // 0:3 1:3 2:3
%v_neg_1ps_pst :: i did not [pos=v,+neg,sb=[+p1,-plr],tm=prf] ; // 0:3 1:3 2:3
%v_neg_2_prs :: you do not [pos=v,+neg,sb=[+p2],tm=imf] ; // 0:3 1:3 2:3

### verb subjects
## 1ps
%v_1ps_prs :: i [pos=v,tam=stm,sb=[+p1,-plr],tm=imf] ; // 0
%v_1ps_pst :: i [pos=v,tam=pst,sb=[+p1,-plr],tm=prf] ; // 0
%v_2p :: you [pos=v,sb=[+p2]] ; // 0

# verb objects
%v_1ps_ob :: [pos=v,ob=[+p1,-plr]] me ; // 1

